modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/CodenameRevy/Additional-Bars/issues" #optional
[[mods]] #mandatory
modId="additionalbars" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Additional Bars" #mandatory
displayURL="https://github.com/CodenameRevy/Additional-Bars" #optional
#logoFile="logo.png" #optional
credits="CodenameRevy" #optional
authors="CodenameRevy" #optional
description='''
This mod adds additional bars to the game that go along with Iron Bars!
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
